### PR TITLE
Fix avatar to allow file names with a parenthesis in the name

### PR DESCRIPTION
**Pull request by Blackbaud-TrevorBurch**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name](https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name](https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name](https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name](https://developer.blackbaud.com/skyux-avatar?_sp.spa=pr-parenthesis-in-file-name)

**Review by Blackbaud-AlexKingman — APPROVED** [review]

**Pull request merged**
